version: '3.1'
services:
    php:
        build: ./docker-conf/php-fpm
        volumes:
            - ./:/var/www/the-shopping-list
            - ./docker-conf/php-fpm/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www/the-shopping-list
            - ./docker-conf/nginx/the-shopping-list.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    db:
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: symf0ny
        ports:
            - "5432:5432"