version: '2'
services:
    php:
        build: ./docker-conf/php-fpm
        volumes:
            - ./:/var/www/the-shopping-list
            - ./docker-conf/php-fpm/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www/the-shopping-list
            - ./docker-conf/nginx/the-shopping-list.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: symf0ny
        ports:
            - "3333:3306"